"""Compile a single-bone static prop from an SMD without studiomdl.

Writes .mdl (v48), .vvd, .dx90.vtx and a box-shaped .phy so the prop can be
used in Garry's Mod. Only what a static prop needs is supported: one bone,
one material, one LOD, and a single convex box for collision.

Usage:
  python3 smd2mdl.py <ref.smd> <out_dir> --name farm/beef.mdl \
      --material beef --cdmaterials models/farm/ --surfaceprop flesh --mass 3
"""
import argparse
import math
import os
import struct
import zlib

import numpy as np

INCH_TO_METER = 0.0254

STUDIO_ANIM_RAWPOS = 0x01
STUDIO_ANIM_RAWROT2 = 0x20
STUDIOHDR_FLAGS_STATIC_PROP = 0x10
STUDIOHDR_FLAGS_AUTOGENERATED_HITBOX = 0x01
BONE_USED_BY_ANYTHING = 0x0007FF00
STRIPGROUP_IS_HWSKINNED = 0x02
STRIP_IS_TRILIST = 0x01


def read_smd(path):
    lines = open(path).read().split('\n')
    i = lines.index('triangles') + 1
    tris = []
    while lines[i].strip() != 'end':
        tris.append([list(map(float, lines[i + k].split()[1:9])) for k in (1, 2, 3)])
        i += 4
    return np.array(tris, dtype=np.float64)


def build_mesh(tris):
    """Weld duplicate vertices and convert to Source conventions."""
    # Source expects clockwise front faces and top-down texture V.
    tris = tris[:, [0, 2, 1], :]
    flat = tris.reshape(-1, 8).copy()
    flat[:, 7] = 1.0 - flat[:, 7]
    key = np.round(flat, 5)
    uniq, inverse = np.unique(key, axis=0, return_inverse=True)
    inverse = inverse.reshape(-1)
    verts = np.zeros((len(uniq), 8))
    verts[inverse] = flat
    pos, nrm, uv = verts[:, 0:3], verts[:, 3:6], verts[:, 6:8]
    nrm /= np.maximum(np.linalg.norm(nrm, axis=1, keepdims=True), 1e-8)
    idx = inverse.reshape(-1, 3)
    return pos, nrm, uv, idx


def compute_tangents(pos, nrm, uv, idx):
    tan = np.zeros_like(pos)
    bit = np.zeros_like(pos)
    p0, p1, p2 = pos[idx[:, 0]], pos[idx[:, 1]], pos[idx[:, 2]]
    t0, t1, t2 = uv[idx[:, 0]], uv[idx[:, 1]], uv[idx[:, 2]]
    e1, e2 = p1 - p0, p2 - p0
    d1, d2 = t1 - t0, t2 - t0
    r = d1[:, 0] * d2[:, 1] - d2[:, 0] * d1[:, 1]
    r = np.where(np.abs(r) < 1e-12, 1.0, 1.0 / np.where(r == 0, 1, r))[:, None]
    sdir = (e1 * d2[:, 1:2] - e2 * d1[:, 1:2]) * r
    tdir = (e2 * d1[:, 0:1] - e1 * d2[:, 0:1]) * r
    for k in range(3):
        np.add.at(tan, idx[:, k], sdir)
        np.add.at(bit, idx[:, k], tdir)
    tan -= nrm * (nrm * tan).sum(1, keepdims=True)
    length = np.linalg.norm(tan, axis=1, keepdims=True)
    fallback = np.cross(nrm, np.array([0.0, 0.0, 1.0]))
    fallback[np.linalg.norm(fallback, axis=1) < 1e-6] = [1.0, 0.0, 0.0]
    tan = np.where(length > 1e-8, tan / np.maximum(length, 1e-8), fallback)
    w = np.where((np.cross(nrm, tan) * bit).sum(1) < 0, -1.0, 1.0)
    return np.hstack([tan, w[:, None]])


class Blob:
    """Byte buffer with deferred int32 patches and a string table."""

    def __init__(self):
        self.data = bytearray()
        self.strings = []  # (field_pos, base_pos, text)

    def tell(self):
        return len(self.data)

    def align(self, n=4):
        while len(self.data) % n:
            self.data.append(0)

    def put(self, fmt, *vals):
        pos = len(self.data)
        self.data += struct.pack('<' + fmt, *vals)
        return pos

    def patch(self, pos, fmt, *vals):
        struct.pack_into('<' + fmt, self.data, pos, *vals)

    def string_ref(self, field_pos, base_pos, text):
        self.strings.append((field_pos, base_pos, text))

    def write_strings(self):
        placed = {}
        for field_pos, base_pos, text in self.strings:
            if text not in placed:
                placed[text] = len(self.data)
                self.data += text.encode('ascii') + b'\0'
            self.patch(field_pos, 'i', placed[text] - base_pos)


def quat64_identity():
    # x, y, z encoded as (v * 1048576 + 1048576) in 21 bits each, w positive.
    q = 1048576 | (1048576 << 21) | (1048576 << 42)
    return struct.pack('<Q', q)


def write_mdl(path, name, material, cdmaterials, surfaceprop, mass, pos, nrm, idx, checksum):
    mins, maxs = pos.min(0), pos.max(0)
    center = (mins + maxs) / 2
    radius = float(np.linalg.norm(pos - center, axis=1).max())
    nverts = len(pos)

    b = Blob()
    hdr = b.put('408x')
    hdr2 = b.put('256x')

    # Bone
    bone = b.tell()
    b.put('ii6i', 0, -1, *([-1] * 6))
    b.put('3f4f3f', 0, 0, 0, 0, 0, 0, 1, 0, 0, 0)
    b.put('3f3f', 1 / 32.0, 1 / 32.0, 1 / 32.0, 1 / 32.0, 1 / 32.0, 1 / 32.0)
    b.put('12f', 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0)
    b.put('4f', 0, 0, 0, 1)
    b.put('6i8i', BONE_USED_BY_ANYTHING, 0, 0, 0, 0, 1, *([0] * 8))
    b.string_ref(bone, bone, 'static_prop')
    b.string_ref(bone + 176, bone, surfaceprop)

    # Hitbox set with one hitbox around the whole model
    hbset = b.tell()
    b.put('iii', 0, 1, 12)
    b.string_ref(hbset, hbset, 'default')
    hbox = b.put('ii3f3fi8i', 0, 0, *mins, *maxs, 0, *([0] * 8))
    b.string_ref(hbox + 32, hbox, '')

    bonetable = b.put('B', 0)
    b.align(4)

    # Animation: one frame, root bone at rest
    anim = b.tell()
    b.put('ii f i i i i 6i i i i i i i i i i hh i f',
          -anim, 0, 30.0, 0, 1, 0, 0, *([0] * 6), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0)
    b.string_ref(anim + 4, anim, '@idle')
    b.align(16)
    animdata = b.tell()
    b.patch(anim + 56, 'i', animdata - anim)
    b.put('BBh', 0, STUDIO_ANIM_RAWPOS | STUDIO_ANIM_RAWROT2, 0)
    b.data += quat64_identity() + b'\0' * 6
    b.align(4)

    # Sequence
    seq = b.tell()
    b.put('53i', *([0] * 53))
    b.patch(seq, 'i', -seq)
    b.string_ref(seq + 4, seq, 'idle')
    b.string_ref(seq + 8, seq, '')
    b.patch(seq + 16, 'ii', -1, 0)  # activity, actweight
    b.patch(seq + 32, '6f', *mins, *maxs)
    b.patch(seq + 56, 'i', 1)  # numblends
    b.patch(seq + 68, 'ii', 1, 1)  # groupsize
    b.patch(seq + 76, 'ii', -1, -1)  # paramindex
    b.patch(seq + 104, 'ff', 0.2, 0.2)  # fade in/out
    weightlist = b.put('f', 1.0)
    animindex = b.put('h', 0)
    b.align(4)
    end_seq = b.tell()
    b.patch(seq + 28, 'i', 212)  # eventindex
    b.patch(seq + 60, 'i', animindex - seq)
    b.patch(seq + 152, 'ii', 212, weightlist - seq)  # autolayerindex, weightlistindex
    b.patch(seq + 168, 'iii', animindex - seq, end_seq - seq, 0)  # iklockindex, keyvalueindex, keyvaluesize
    b.patch(seq + 184, 'i', end_seq - seq)  # activitymodifierindex

    # Body part -> model -> mesh
    bodypart = b.put('iiii', 0, 1, 1, 16)
    b.string_ref(bodypart, bodypart, 'body')
    model = b.tell()
    b.data += os.path.splitext(os.path.basename(name))[0].encode('ascii').ljust(64, b'\0')
    b.put('i f i i i i i i i i i ii 8i', 0, radius, 1, 148, nverts, 0, 0, 0, 0, 0, 0, 0, 0, *([0] * 8))
    mesh = b.put('iiiiiiiii3f', 0, -148, nverts, 0, 0, 0, 0, 0, 0, *center)
    b.put('i8i8i', 0, *([nverts] * 8), *([0] * 8))

    texture = b.put('16i', *([0] * 16))
    b.string_ref(texture, texture, material)
    cdtex = b.put('i', 0)
    b.string_ref(cdtex, 0, cdmaterials)
    skins = b.put('h', 0)
    b.align(4)
    keyvalues = b.tell()

    b.string_ref(hdr2 + 20, hdr2, name)
    b.string_ref(hdr + 308, 0, surfaceprop)
    b.string_ref(hdr + 348, 0, '')
    b.write_strings()
    b.align(4)
    length = b.tell()

    eye = (0.0, 0.0, 0.0)
    b.patch(hdr, '4sii', b'IDST', 48, checksum)
    b.data[hdr + 12:hdr + 76] = name.encode('ascii')[:63].ljust(64, b'\0')
    b.patch(hdr + 76, 'i', length)
    b.patch(hdr + 80, '3f3f3f3f3f3f', *eye, *center, *mins, *maxs, 0, 0, 0, 0, 0, 0)
    b.patch(hdr + 152, 'i', STUDIOHDR_FLAGS_STATIC_PROP | STUDIOHDR_FLAGS_AUTOGENERATED_HITBOX)
    b.patch(hdr + 156, 'ii ii ii ii ii ii', 1, bone, 0, hbset, 1, hbset, 1, anim, 1, seq, 0, 0)
    b.patch(hdr + 204, 'ii ii iii ii ii', 1, texture, 1, cdtex, 1, 1, skins, 1, bodypart, 0, hbset)
    b.patch(hdr + 248, 'iii', 0, keyvalues, keyvalues)
    b.patch(hdr + 260, '12i', *([0, keyvalues] * 6))
    b.patch(hdr + 312, 'iiii f i ii i', keyvalues, 0, 0, keyvalues, mass, 1, 0, keyvalues, 0)
    b.patch(hdr + 352, 'iii i', 0, keyvalues, 0, bonetable)
    b.patch(hdr + 384, 'ii f i i i', 0, keyvalues, 0.0, 0, hdr2, 0)
    b.patch(hdr2, 'iiifi', 0, keyvalues, 0, 0.0, 0)

    with open(path, 'wb') as f:
        f.write(b.data)
    return mins, maxs


def write_vvd(path, pos, nrm, uv, tan, checksum):
    n = len(pos)
    out = bytearray(struct.pack('<4sii i8i iiii', b'IDSV', 4, checksum, 1, *([n] * 8), 0, 64, 64, 64 + n * 48))
    vtype = np.dtype([('w', '<f4', (3,)), ('b', 'i1', (3,)), ('nb', 'u1'), ('p', '<f4', (3,)),
                      ('n', '<f4', (3,)), ('t', '<f4', (2,))])
    v = np.zeros(n, vtype)
    v['w'][:, 0] = 1.0
    v['nb'] = 1
    v['p'], v['n'], v['t'] = pos, nrm, uv
    out += v.tobytes()
    out += tan.astype('<f4').tobytes()
    with open(path, 'wb') as f:
        f.write(out)


def write_vtx(path, nverts, idx, checksum):
    assert nverts < 65536, 'too many vertices for one strip group'
    indices = idx.reshape(-1).astype('<u2')
    out = bytearray()
    out += struct.pack('<iiHHiiiiii', 7, 24, 53, 9, 3, checksum, 1, 0, 1, 36)
    out += struct.pack('<ii', 1, 8)            # body part
    out += struct.pack('<ii', 1, 8)            # model
    out += struct.pack('<iif', 1, 12, 0.0)     # lod
    out += struct.pack('<iiB', 1, 9, 0)        # mesh
    sg = len(out)
    vert_off = 25 + 27
    idx_off = vert_off + nverts * 9
    strip_bsc = idx_off + len(indices) * 2 - 25
    out += struct.pack('<iiiiiiB', nverts, vert_off, len(indices), idx_off, 1, 25, STRIPGROUP_IS_HWSKINNED)
    out += struct.pack('<iiiihBii', len(indices), 0, nverts, 0, 1, STRIP_IS_TRILIST, 1, strip_bsc)
    vt = np.zeros(nverts, np.dtype([('bw', 'u1', (3,)), ('nb', 'u1'), ('id', '<u2'), ('bid', 'i1', (3,))]))
    vt['bw'] = (0, 1, 2)
    vt['nb'] = 1
    vt['id'] = np.arange(nverts)
    out += vt.tobytes()
    out += indices.tobytes()
    assert len(out) - sg - 25 == strip_bsc
    out += struct.pack('<ii', 0, 0)            # bone state change: hw 0 -> bone 0
    matlist = len(out)
    out += struct.pack('<ii', 0, 0)
    struct.pack_into('<i', out, 24, matlist)
    with open(path, 'wb') as f:
        f.write(out)


def to_ivp(p):
    return np.array([p[0], -p[2], p[1]]) * INCH_TO_METER


# Box hull topology taken from a studiomdl-compiled box ledge. Corner order:
# (x, y_ivp, z_ivp) signs.
BOX_CORNERS = [(1, 1, 1), (-1, -1, 1), (1, -1, 1), (-1, 1, 1),
               (1, -1, -1), (-1, -1, -1), (1, 1, -1), (-1, 1, -1)]
BOX_TRIANGLES = bytes.fromhex(
    '00b0000000000600010009000200100001a00000000014000300' '1b000100fa7f'
    '02700000010006000400070002' '00f77f'
    '03600000010016000500' '1d000400fa7f'
    '04900000' '0200f97f04000500' '0000f07f'
    '0580000004001a0006000800' '0000fb7f'
    '06300000' '0300ec7f00000300' '07000b00'
    '07200000' '0700fd7f0000f87f' '06000f00'
    '08500000' '0100e57f03000300' '0500ea7f'
    '09400000' '0500fd7f0300f57f' '07000200'
    '0a100000' '0500fe7f07000300' '0400e37f'
    '0b000000' '0400fd7f0700f17f' '0600e67f')


def write_phy(path, mins, maxs, mass, surfaceprop, checksum):
    lo, hi = to_ivp(mins), to_ivp(maxs)
    imin, imax = np.minimum(lo, hi), np.maximum(lo, hi)
    c = (imin + imax) / 2
    h = (imax - imin) / 2
    pts = [c + h * np.array(s) for s in BOX_CORNERS]
    radius = float(np.linalg.norm(h))
    inertia = ((h[1] ** 2 + h[2] ** 2) / 3, (h[0] ** 2 + h[2] ** 2) / 3, (h[0] ** 2 + h[1] ** 2) / 3)
    box_sizes = [min(255, math.ceil(e * 250 / radius)) for e in h]

    ledge = struct.pack('<iiiHH', 208, 0, 0x1504, 12, 0) + BOX_TRIANGLES
    assert len(ledge) == 208
    for p in pts:
        ledge += struct.pack('<4f', *p, 0.0)
    surface_size = 48 + len(ledge) + 28
    surface = struct.pack('<7f', *c, *inertia, radius)
    surface += struct.pack('<IIii4s', 0xF7 | (surface_size << 8), surface_size - 28, 0, 0, b'IVPS')
    surface += ledge
    surface += struct.pack('<ii4f4B', 0, -len(ledge), *c, radius, *box_sizes, 0)
    assert len(surface) == surface_size

    solid = b'VPHY' + struct.pack('<HHI3fI', 0x100, 0, surface_size, 1.0, 1.0, 1.0, 0) + surface
    volume = float(np.prod(np.array(maxs) - np.array(mins)))
    kv = ('solid {\n"index" "0"\n"name" "static_prop"\n"mass" "%f"\n"surfaceprop" "%s"\n'
          '"damping" "0.000000"\n"rotdamping" "0.000000"\n"inertia" "1.000000"\n"volume" "%f"\n}\n'
          'editparams {\n"rootname" ""\n"totalmass" "%f"\n"concave" "0"\n}\n') % (mass, surfaceprop, volume, mass)
    with open(path, 'wb') as f:
        f.write(struct.pack('<4i', 16, 0, 1, checksum))
        f.write(struct.pack('<I', len(solid)) + solid)
        f.write(kv.encode('ascii') + b'\0')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('smd')
    ap.add_argument('out_dir')
    ap.add_argument('--name', required=True, help='model path relative to models/, e.g. farm/beef.mdl')
    ap.add_argument('--material', required=True)
    ap.add_argument('--cdmaterials', required=True)
    ap.add_argument('--surfaceprop', default='default')
    ap.add_argument('--mass', type=float, default=10.0)
    a = ap.parse_args()

    tris = read_smd(a.smd)
    pos, nrm, uv, idx = build_mesh(tris)
    tan = compute_tangents(pos, nrm, uv, idx)
    checksum = zlib.crc32(open(a.smd, 'rb').read() + a.name.encode()) & 0x7FFFFFFF

    base = os.path.join(a.out_dir, os.path.splitext(a.name)[0])
    os.makedirs(os.path.dirname(base), exist_ok=True)
    mins, maxs = write_mdl(base + '.mdl', a.name, a.material, a.cdmaterials.replace('/', '\\'),
                           a.surfaceprop, a.mass, pos, nrm, idx, checksum)
    write_vvd(base + '.vvd', pos, nrm, uv, tan, checksum)
    write_vtx(base + '.dx90.vtx', len(pos), idx, checksum)
    write_phy(base + '.phy', mins, maxs, a.mass, a.surfaceprop, checksum)
    print('%s: %d verts, %d tris, bounds %s - %s' % (a.name, len(pos), len(idx),
                                                     np.round(mins, 2), np.round(maxs, 2)))


if __name__ == '__main__':
    main()
